CREATE TABLE IF NOT EXISTS users  (
    id INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    username VARCHAR(255) NOT NULL,
    hash VARCHAR(255) NOT NULL,
    salt VARCHAR(255) NOT NULL,
    isadmin BOOLEAN NOT NULL
);

CREATE TABLE IF NOT EXISTS posts (
    id INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    title VARCHAR(255) NOT NULL,
    text VARCHAR(255) NOT NULL,
    author INT NOT NULL REFERENCES users(id)
);